baseURL = "https://LearnAL0T.github.io/"
title = "LAL"
theme = "PaperMod"
enableEmoji = true  # 允许使用emoji

[params]
  math = true  # 启用数学公式支持
  mathUse = "katex"

[markup.goldmark.renderer]
  unsafe = true        # 允许原始HTML（必须！）
